logging:
  level:
    root: INFO # Mantiene librerías externas en INFO
    com.example.sqsmicro: DEBUG
spring:
  application:
    name: airport-c
  main:
    allow-bean-definition-overriding: true
  cloud:
    aws:
      region:
        static: us-east-1 # Una región arbitraria
      # Configuración específica para SQS que apunta a ElasticMQ
      sqs:
        endpoint: http://elasticmq:9324
      credentials:
        # Credenciales dummy que cumplen con el requisito del SDK de AWS
        access-key: dummy
        secret-key: dummy
config:
  server:
    url: http://localhost:8888
app:
  client:
    id: airport-c
    secret: secret-c-456